services:
  postgresdb:
    image: postgres:11
    container_name: blog_db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: blog
    ports:
      - "5432:5432"
    volumes:
      - ./database/create.sql:/docker-entrypoint-initdb.d/create.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  node-server:
    build: .
    environment:
      - POSTGRES_URL=postgres://root:123456@blog_db:5432/blog
    ports:
      - "3000:3000"
    volumes:
      - .:/server
    env_file: ./.env
    working_dir: /server
    command: ["npm", "start"]
    networks:
      - backend
    depends_on:
      - postgresdb

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
